name: malioc_diff
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: any
  colorize: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  malioc_diff: